---
title: "PrismLows"
author: "A Hessl"
date: "1/3/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Read and extract annual winter lows from PRISM Data

```{r setup}
rm(list=ls())
library(lubridate)
library(tidyverse)
```

Read in all prism files in data/daily_cv directory, reformat and arrange as a list
```{r read.prism}
#call function read.prism.R
source('Functions/read.prism.R')
pgrid.list <- read.prism("daily_cv")
```



```{r min monT}
#Select one gridbox file from the list of grids
pgrid <- pgrid.list$pgrid.df

## Minimum monthly temperatures
mon.min <- pgrid %>% group_by(year=year(pdate), month=month(pdate)) %>% summarize(m.min=min(tmin))

#add readable time variable for plotting
mon.min$pdate <- paste0(mon.min$year, "-", mon.min$month, "-1")
```

```{r plot min monT}
plot(as.Date(mon.min$pdate), mon.min$m.min, type='l', xlab="Year", ylab="MinMonT(C)", main="Min Monthly T")
```

```{r threshold}
#Find duration of the low below a critical threshold
thresh <- 0
pgrid$thresh <- pgrid$tmax < thresh

pgrid$year <- year(pgrid$pdate)
pgrid$month <- month(pgrid$pdate)
pgrid$day <- day(pgrid$pdate)

#Adjust Nov and Dec to be subsequent year
prev.win <- c(11, 12)
adj.year <- ifelse (pgrid$month %in% prev.win, pgrid$year+1, pgrid$year)
pgrid$year <- adj.year

thresh.event <- pgrid[pgrid$thresh %in% 'TRUE', -c(1:5)] 

#Count number of days tmax < thresh
thresh.count <- aggregate(thresh.event, by=list(thresh.event$year), sum)[,1:2]

barplot(thresh.count$thresh[-38], names=thresh.count$Group.1[-38], ylab="Count (neg degree days)", xlab="Year")

```

```{r negative degree days}
#Select only events below thresh and only needed cols
neg.days <- pgrid[pgrid$thresh %in% 'TRUE', c("tmax", "year", "month")] 

#cumulative sum of negative degree days
neg.dd <- aggregate(neg.days, by=list(neg.days$year), sum)[,c(1,2)]
names(neg.dd) <- c("Year", "sumTmax")

barplot(neg.dd$sumTmax, names=neg.dd$Year, ylim=c(0,-350), ylab="Sum (neg degree days)", xlab="Year")

```


```{r duration}
runs <- rle(pgrid$thresh)

pgrid$runs <- rep(runs$lengths, runs$lengths) #add a new vector that tells the lengths and positions of the runs

#give each run a unique identifier to aggregate on
events <- length(runs$values)
pgrid$event.id <- rep(1:events, c(runs$lengths))
```


Events below threshold (TRUE) & longer than 5 days are kept, group by year and month
```{r events plot}
long.event <- pgrid[pgrid$thresh %in% 'TRUE' & pgrid$runs >= 5, -c(1:6)] 

#start date and length of each run below threshold
long.st.date <- aggregate(long.event, by=list(long.event$event.id), min)

num.long.yr <- aggregate(long.st.date, by=list(long.st.date$year), length)[, c(1, 6)]

barplot(num.long.yr$runs[-37], names=num.long.yr$Group.1[-37], ylab="No. Long Freeze (>5 days)", xlab="Year")

```

Read in Monthly Data (tmin, tmax)

```{r plot monthly data}
rm(list=ls())
library(lubridate)
library(tidyverse)
source('Functions/read.prism.R')
pgrid.list <- read.prism("mon_cv")

pgridm <- dataFiles[[1]] #happens to be 1st file
#add readable time variable for plotting

pgridm$pdate <- paste0(pgridm$pdate, "-01")

pgridm_post1960 <- pgridm[pgridm$pdate >= "1960-01-01",]
plot(as.Date(pgridm_post1960$pdate), pgridm_post1960$tmin, type='l')
#truncate to 1960:2018?

```


```{r plot annual min}
#adjust Nov, Dec to subsequent year
pgridm$year <- year(pgridm$pdate)
pgridm$month <- month(pgridm$pdate)

adj.year <- ifelse (pgridm$month %in% prev.win, pgridm$year+1, pgridm$year)
pgridm$year <- adj.year

win.min <- aggregate(pgridm, by=list(pgridm$year), min)[,c(4,7)]
plot(win.min$year, win.min$tmin, type='l', xlab='Year', ylab='MinMonT')
text(1965, -16, "Ohio R Froze")
```